# Generated by Django 5.2.7 on 2025-10-14 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название книги')),
                ('author', models.CharField(max_length=100, verbose_name='Автор')),
                ('year', models.IntegerField(verbose_name='Год издания')),
                ('pages', models.IntegerField(verbose_name='Количество страниц')),
                ('genre', models.CharField(blank=True, max_length=50, verbose_name='Жанр')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
        ),
    ]
